### ISSUE TITLE
workflow

### ISSUE THREAD

**Issue by maxisam** [fieryapi/dot-net-samples#1]
Is there a way to post a job and assign specific workflow?

**Comment by yusukeko** [comment]
Hi Sam,

Yes, you can send a job to Virtual Printer or Fiery Preset queue - works like templates.
You can get the list of queues by GET  /live/api/v4/queues. Once you know the queue id, specify it when you POST jobs.

Thanks,
Yusuke

**Comment by maxisam** [comment]
Thank you for your fast response! 

Now I am using a virtual printer like a queue and trying to assign a specific preset for a job then push this job to this virtual printer. 

From what you said, I think it should be more like pushing a job to a virtual printer with a specific preset. And a virtual printer is for one job preset. 

Do I understand it correctly?

Btw, I am using V2 Api. How do I upgrade to V4?

**Comment by maxisam** [comment]
I just tried to assign the virtual printer to a job. (in v2, it is "logical printer").

It does set it to the workflow, However, in the property of the job, the preset attribute is undefined.

I think it is because the preset is actually apply to the virtual print not the job. 

That brings me another question. Is it possible to assing a "preset" to a job?

**Comment by yusukeko** [comment]
Hi Sam,

Yes it's possible to set preset to a job. Again you need to get preset IDs from GET /live/api/v4/presets and specify it when you POST jobs with "preset" instead of "queue"

Also, I recommend updating your Fiery API to v4.

Thanks,
Yusuke
